apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: redeye18/client
      context: client
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
          - dest: .
            src: "src/**/*.tsx"
          - dest: .
            src: "src/**/*.css"
    - image: redeye18/posts
      context: posts-service
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: redeye18/comments
      context: comments-service
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: redeye18/query
      context: query-service
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: redeye18/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: redeye18/moderation
      context: moderation-service
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
